version: "2"
services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  bridge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
